# Generated by Django 5.0.2 on 2024-05-11 01:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
