# Generated by Django 5.0.2 on 2024-05-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0002_alter_interaction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='interaction',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
